/* Generated by Together */

package com.hzjc.report.service;

import com.hzjc.wsstruts.exception.DAOException;
import com.hzjc.wsstruts.exception.ServiceException;
import com.hzjc.wsstruts.service.WSService;
import com.hzjc.wsstruts.vo.*;
import java.util.List;
/**
 *
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口管理系统Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: 浙江金铖新技术有限公司</p>
 * @author kgb_hz@126.com,kgb@primetech.com.cn
 * @version 1.0
 */
public interface ReportService
    extends WSService {

  /**
   *
   * @param strSQL
   * @return
   * @throws DAOException
   * @throws ServiceException
   */
  String buildReportXml(String strSQL, String strSQLType) throws DAOException,
      ServiceException;
  /**
   *
   * @param cdsTjrq
   * @param cdsTjjwh
   * @return
   * @throws DAOException
   * @throws ServiceException
   */
  List BbtjData(CdsVO cdsTjrq[],CdsVO cdsTjjwh[])throws DAOException,
      ServiceException;
  /**
   *
   * @param cdsJcwh
   * @param cdsTjrq
   * @return
   * @throws DAOException
   * @throws ServiceException
   */
  VoQueryResult QryBbtjny(CdsVO cdsJcwh[],CdsVO cdsTjrq[])throws DAOException,ServiceException;
}
