/* Generated by Together */

package com.hzjc.wsstruts.common.db;

import com.hzjc.wsstruts.exception.*;
import java.io.*;
import org.apache.commons.logging.*;
import java.util.*;

/**
 *
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @Kansanku(kgb_hz@126.com)
 * @version 1.0
 */
public class PropertiesDbConfig
    extends DbConfig {

  //日志处理
  protected static Log _log = LogFactory.getLog(PropertiesDbConfig.class);
  private static DbConfig _config = null;
  private static Properties _properties = null;
  private static String _propertiesfilename = "/hibernate.properties";

  /**
   * 保护构造子
   */
  protected PropertiesDbConfig() {
    initCfg();
  }

  /**
   * 初始化
   */
  private void initCfg() throws ControlException {
    try {
      _properties = new Properties();
      InputStream is = PropertiesDbConfig.class.getResourceAsStream(
          _propertiesfilename);
      _properties.load(is);
    }
    catch (IOException ex) {
      throw new ControlException(WSErrCode.ERR_CTRL_LOAD_DBCONFIG, ex);
    }
  }

  /**
   * 根据配置键值返回对应的配置
   * @param strKey
   * @return
   */
  public String getProperty(String strKey) {
    String strValue = "";
    if (_properties == null) {
      initCfg();
    }
    strValue = _properties.getProperty(strKey);
    return strValue;
  }

  /**
   *
   * @return
   */
  public static synchronized DbConfig getInstance() throws ControlException {
    if (_config == null) {
      try {
        _config = new PropertiesDbConfig();
      }
      catch (Exception ex) {
        throw new ControlException(WSErrCode.ERR_CTRL_LOAD_DBCONFIG, ex);
      }
    }
    return _config;
  }

}
