/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.8
 * Generated at: 2020-10-12 03:25:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.cx;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.hzjc.hz2004.base.login.LoginFilter;
import java.util.*;
import java.net.*;
import com.hzjc.hz2004.base.*;
import com.hzjc.hz2004.util.*;
import com.hzjc.hz2004.base.login.*;
import com.hzjc.util.*;
import com.hzjc.hz2004.po.PoXT_YHSJFWB;
import com.hzjc.hz2004.po.PoPERSON_DY_SET;
import com.hzjc.hz2004.po.PoXT_XTGNB;

public final class rkzl_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/jsp/cx/../config.jsp", Long.valueOf(1602465772454L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hzjc.hz2004.base");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.hzjc.hz2004.base.login");
    _jspx_imports_packages.add("com.hzjc.hz2004.util");
    _jspx_imports_packages.add("com.hzjc.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.hzjc.hz2004.po.PoXT_YHSJFWB");
    _jspx_imports_classes.add("com.hzjc.hz2004.po.PoXT_XTGNB");
    _jspx_imports_classes.add("com.hzjc.hz2004.po.PoPERSON_DY_SET");
    _jspx_imports_classes.add("com.hzjc.hz2004.base.login.LoginFilter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


	String path = request.getContextPath();
	String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+ path+"/";
	String sysDate = StringUtils.getServiceDate();
	String dkqlx = "2";//è¯»å¡å¨é»è®¤ä¸º2 åè§
	int ryxxsdFlag = 0;
	int ryxxjsFlag = 0;
	AuthToken authToken = BaseContext.getUser();
	if(authToken!=null){
		PoPERSON_DY_SET poPERSON_DY_SET = authToken.getPersonDySet();
		if(poPERSON_DY_SET!=null){
			dkqlx = poPERSON_DY_SET.getDkqlx();
		}
		if(authToken.isAdmin()){
			ryxxsdFlag = 1;
			ryxxjsFlag = 1;
		}else{
			List<PoXT_XTGNB>  xtgnb = authToken.getXtgn();
			for(PoXT_XTGNB gn:xtgnb){
				if(gn.getGnbh().equals("F0000")){//äººåä¿¡æ¯éå®
					ryxxsdFlag = 1;
				}else if(gn.getGnbh().equals("F0001")){//äººåä¿¡æ¯è§£é
					ryxxjsFlag = 1;
				}
			}
		}
	}
	response.setHeader("Cache-Control","no-store");  
	response.setHeader("Pragrma","no-cache");  
	response.setDateHeader("Expires",0); 

      out.write("<Script Lanaguage=\"JavaScript\">\r\n");
      out.write("\tvar xmdz = '");
      out.print(basePath);
      out.write("';\r\n");
      out.write("\tvar sysDate = '");
      out.print(sysDate);
      out.write("';\r\n");
      out.write("\t/** \r\n");
      out.write("\t\t2018.10.25\r\n");
      out.write("\t\tÃ¦ÂÂ°Ã¥Â¢Â\tÃ¥ÂÂÃ¦ÂÂ°\r\n");
      out.write("\t\tÃ¨Â¿ÂÃ¥ÂÂºÃ¥ÂÂ°Ã§ÂÂÃ¥Â¸ÂÃ¥ÂÂ¿Ã¥ÂÂº - Ã¥Â®ÂÃ¥Â¾Â½Ã§ÂÂ\r\n");
      out.write("\t\tÃ¨Â¿ÂÃ¥ÂÂ¥Ã¤Â¸ÂÃ¥ÂÂ¡/Ã¨Â¿ÂÃ¥ÂÂ¥Ã¥Â®Â¡Ã¦ÂÂ¹Ã¤Â½Â¿Ã§ÂÂ¨\r\n");
      out.write("\t*/\r\n");
      out.write("\tvar sysQcdq = \"34\";\r\n");
      out.write("\tvar dkqlx = '");
      out.print(dkqlx);
      out.write("';\r\n");
      out.write("\tvar ryxxsdFlag = '");
      out.print(ryxxsdFlag);
      out.write("';\r\n");
      out.write("\tvar ryxxjsFlag = '");
      out.print(ryxxjsFlag);
      out.write("';\r\n");
      out.write("\tvar baseurl = '");
      out.print(basePath);
      out.write("';\r\n");
      out.write("\tfunction forbidBackSpace(e) {\r\n");
      out.write("\t\t   var ev = e || window.event; //è·åeventå¯¹è±¡ \r\n");
      out.write("\t\t   var obj = ev.target || ev.srcElement; //è·åäºä»¶æº \r\n");
      out.write("\t\t   var t = obj.type || obj.getAttribute('type'); //è·åäºä»¶æºç±»å \r\n");
      out.write("\t\t   //è·åä½ä¸ºå¤æ­æ¡ä»¶çäºä»¶ç±»å \r\n");
      out.write("\t\t   var vReadOnly = obj.readOnly;\r\n");
      out.write("\t\t   var vDisabled = obj.disabled;\r\n");
      out.write("\t\t   //å¤çundefinedå¼æåµ \r\n");
      out.write("\t\t   vReadOnly = (vReadOnly == undefined) ? false : vReadOnly;\r\n");
      out.write("\t\t   vDisabled = (vDisabled == undefined) ? true : vDisabled;\r\n");
      out.write("\t\t   //å½æ²Backspaceé®æ¶ï¼äºä»¶æºç±»åä¸ºå¯ç æåè¡ãå¤è¡ææ¬çï¼ \r\n");
      out.write("\t\t   //å¹¶ä¸readOnlyå±æ§ä¸ºtrueædisabledå±æ§ä¸ºtrueçï¼åéæ ¼é®å¤±æ \r\n");
      out.write("\t\t   var flag1 = ev.keyCode == 8 && (t == \"password\" || t == \"text\" || t == \"textarea\") && (vReadOnly == true || vDisabled == true);\r\n");
      out.write("\t\t   //å½æ²Backspaceé®æ¶ï¼äºä»¶æºç±»åéå¯ç æåè¡ãå¤è¡ææ¬çï¼åéæ ¼é®å¤±æ \r\n");
      out.write("\t\t   var flag2 = ev.keyCode == 8 && t != \"password\" && t != \"text\" && t != \"textarea\";\r\n");
      out.write("\t\t   //å¤æ­ \r\n");
      out.write("\t\t   if (flag2 || flag1) return false;\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t//ç¦æ­¢åéé® ä½ç¨äºFirefoxãOpera\r\n");
      out.write("\t\tdocument.onkeypress = forbidBackSpace;\r\n");
      out.write("\t\t//ç¦æ­¢åéé®  ä½ç¨äºIEãChrome\r\n");
      out.write("\t\tdocument.onkeydown = forbidBackSpace;\r\n");
      out.write("\t \r\n");
      out.write("</Script>");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t    <title>人口总览</title>\r\n");
      out.write("\t    <meta name=\"renderer\" content=\"webkit\">\r\n");
      out.write("\t    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0\">\r\n");
      out.write("\t    <!-- <link rel=\"stylesheet\" href=\"../css/index.css\" media=\"all\"> -->\r\n");
      out.write("\t    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/index.css\"  media=\"all\">\r\n");
      out.write("\t    <script src=\"../js/jquery.min.js\"></script>\r\n");
      out.write("\t    <script src=\"../js/echarts.min.js\"></script>\r\n");
      out.write("\t    <script src=\"../js/anhui.js\"></script>\r\n");
      out.write("\t    <script src=\"../js/shine.js\"></script>\r\n");
      out.write("\t    <script src=\"../js/macarons.js\"></script>\r\n");
      out.write("\t    <script src=\"../js/infographic.js\"></script>\r\n");
      out.write("\t    <script src=\"../js/dark.js\"></script>\r\n");
      out.write("\t    <script src=\"../js/roma.js\"></script>\r\n");
      out.write("\t    <script src=\"../js/common.js\"></script>\r\n");
      out.write("\t    <script type=\"text/javascript\" src=\"../js/ext/ext.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../js/commFrames.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"../static/cx/rkzl.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  <div class=\"sne-layout\">\r\n");
      out.write("    <div class=\"sne-layout-box-top\">\r\n");
      out.write("        <div class=\"sne-layout-box-top-left\"></div>\r\n");
      out.write("        <div class=\"sne-layout-box-top-middle\">\r\n");
      out.write("            <span style=\"display:inline-block;float:right;width:250px;margin-top:20px;font-size:15px;color:yellow;\" id=\"timego\"></span>\r\n");
      out.write("            <div class=\"sne-layout-box-top-title\" id=\"title_head\">安徽户政统一服务平台—人口数据分析\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sne-layout-box-top-menu\" id=\"title_menu\" style=\"display:none;\">\r\n");
      out.write("                <div class=\"sne-layout-box-top-menu-item\">\r\n");
      out.write("                    <a href=\"echartsZlNew?theme=1\">macarons</a>\r\n");
      out.write("                    <a href=\"echartsZlNew?theme=2\">shine</a>\r\n");
      out.write("                    <a href=\"echartsZlNew?theme=3\">dark</a>\r\n");
      out.write("                    <a href=\"echartsZlNew?theme=4\">infographic</a>\r\n");
      out.write("                    <a href=\"echartsZlNew?theme=5\">roma</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sne-layout-box-top-right\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sne-layout-box-middle\">\r\n");
      out.write("        <div class=\"sne-layout-box-middle-left\">\r\n");
      out.write("            <div class=\"sne-layout-box-middle-left-img\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sne-layout-box-middle-middle\">\r\n");
      out.write("            <!--正文内容开始-->\r\n");
      out.write("            <!--左-->\r\n");
      out.write("            <div class=\"sne-content-layout1\">\r\n");
      out.write("                <!--box1 start-->\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h19\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">人口总览\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2\">\r\n");
      out.write("                            <div style=\"position: relative;\">\r\n");
      out.write("                                <div style=\"position: absolute;width: 168px;top: 10px;left: -30px;right: 0;bottom: 0;margin: 0 auto;text-align: left;\">\r\n");
      out.write("                                    <div style=\"color: #bfc4d7;font-size: 20px;line-height: 20px;\">\r\n");
      out.write("                                    \t\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div style=\"color: #bfc4d7;font-size: 14px;line-height: 14px;\">\r\n");
      out.write("                                    \t总人口数：\r\n");
      out.write("                                    \t<a style=\"color: #deda00;font-size: 18px;line-height: 18px;\" id=\"data_1_div_zrkstotal\">\r\n");
      out.write("                                    \t\t0\r\n");
      out.write("                                    \t</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div style=\"color: #bfc4d7;font-size: 14px;line-height: 14px;\">\r\n");
      out.write("                                    \t 总户数：\r\n");
      out.write("                                    \t<a style=\"color: #deda00;font-size: 18px;line-height: 18px;\" id=\"data_1_div_zhstotal\">\r\n");
      out.write("                                    \t\t0\r\n");
      out.write("                                    \t</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div style=\"color: #bfc4d7;font-size: 14px;line-height: 14px;\">\r\n");
      out.write("                                    \t总流入数：\r\n");
      out.write("                                    \t<a style=\"color: #deda00;font-size: 18px;line-height: 18px;\" id=\"data_1_div_zlrstotal\">\r\n");
      out.write("                                    \t\t0\r\n");
      out.write("                                    \t</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div style=\"color: #bfc4d7;font-size: 14px;line-height: 14px;\">\r\n");
      out.write("                                    \t总流出数：\r\n");
      out.write("                                    \t<a style=\"color: #deda00;font-size: 18px;line-height: 18px;\" id=\"data_1_div_zlcstotal\">\r\n");
      out.write("                                    \t\t0\r\n");
      out.write("                                    \t</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- <div   id=\"data_1_div\" class=\"liujfchart\" style=\"height: 118px;width:271px;margin-left: -10px;\"></div> -->\r\n");
      out.write("                            </div>                        \r\n");
      out.write("                            <!--loading-->\r\n");
      out.write("                            <!--<div class=\"sne-loading\" >-->\r\n");
      out.write("                                <!--<img src=\"../images/loading-small.gif\" alt=\"\">-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--echart 1-->\r\n");
      out.write("                            <!--<img src=\"../images/echart_1.png\" alt=\"\" >-->\r\n");
      out.write("                            <!-- <div id=\"data_1_div\" class=\"liujfchart\" style=\"height: 230px;width:280px;margin-left: -10px;\"></div> -->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h19\"> </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--box1 end-->\r\n");
      out.write("\r\n");
      out.write("                <!--box1 start-->\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h35\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">总人口性别占比\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2\">\r\n");
      out.write("                            <!--echart 5-->\r\n");
      out.write("                            <!--<img src=\"../images/echart_5.png\" alt=\"\">-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"position: relative;\">\r\n");
      out.write("                                <div style=\"position: absolute;width: 68px;top: 50px;left: 10px;right: 0;bottom: 0;margin: 0 auto;text-align: center;\">\r\n");
      out.write("                                    <div style=\"color: #deda00;font-size: 18px;line-height: 18px;\" id=\"data_4_div_total\"></div>\r\n");
      out.write("                                    <div style=\"color: #bfc4d7;font-size: 14px;line-height: 14px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--echart 4-->\r\n");
      out.write("                                <!--<img src=\"../images/echart_4.png\" alt=\"\">-->\r\n");
      out.write("                                <div   id=\"data_4_div\" class=\"liujfchart2\" style=\"height: 118px;width:271px;\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h35\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--box1 end-->\r\n");
      out.write("\r\n");
      out.write("                <!--box1 start-->\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h63\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">人口年龄分布\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2\">\r\n");
      out.write("                            <!--echart 7-->\r\n");
      out.write("                            <!--<img src=\"../images/echart_5.png\" alt=\"\">-->\r\n");
      out.write("                            <div style=\"position: relative;\">\r\n");
      out.write("                                <div style=\"position: absolute;width: 68px;top: 50px;left: 10px;right: 0;bottom: 0;margin: 0 auto;text-align: center;\">\r\n");
      out.write("                                    <div style=\"color: #deda00;font-size: 18px;line-height: 18px;\" id=\"data_7_div_total\"></div>\r\n");
      out.write("                                    <div style=\"color: #bfc4d7;font-size: 14px;line-height: 14px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--echart 4-->\r\n");
      out.write("                                <!--<img src=\"../images/echart_4.png\" alt=\"\">-->\r\n");
      out.write("                                <div   id=\"data_7_div\" class=\"liujfchart2\" style=\"height: 145px;width:271px;\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h63\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--box1 end-->\r\n");
      out.write("\r\n");
      out.write("                <!--box1 start-->\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h35\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">当年迁入本省与外省占比分析\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2\">\r\n");
      out.write("                            <!--echart 5-->\r\n");
      out.write("                            <!--<img src=\"../images/echart_5.png\" alt=\"\">-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <div style=\"position: relative;\">\r\n");
      out.write("                                <div style=\"position: absolute;width: 68px;top: 50px;left: 10px;right: 0;bottom: 0;margin: 0 auto;text-align: center;\">\r\n");
      out.write("                                    <div style=\"color: #deda00;font-size: 18px;line-height: 18px;\" id=\"data_5_div_total\"></div>\r\n");
      out.write("                                    <div style=\"color: #bfc4d7;font-size: 14px;line-height: 14px;\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--echart 4-->\r\n");
      out.write("                                <!--<img src=\"../images/echart_4.png\" alt=\"\">-->\r\n");
      out.write("                                <div   id=\"data_5_div\" class=\"liujfchart2\" style=\"height: 118px;width:271px;\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h35\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--box1 end-->\r\n");
      out.write("\r\n");
      out.write("                <!--box1 start-->\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h36\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">当年流入流出占比\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2\">\r\n");
      out.write("                            <!--echart 3-->\r\n");
      out.write("                            <!--<img src=\"../images/echart_3.png\" alt=\"\">-->\r\n");
      out.write("                            <div id=\"data_3_div\"  class=\"liujfchart2\" style=\"height: 118px;width:261px;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h36\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--box1 end-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--中-->\r\n");
      out.write("            <div class=\"sne-content-layout2\">\r\n");
      out.write("                <!--box1 start-->\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h464\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">全省行政分布\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2\">\r\n");
      out.write("                            <!--<div class=\"sne-radio\">-->\r\n");
      out.write("                                <!--<input id=\"item1\" type=\"radio\" name=\"item\" value=\"行政案件\" >-->\r\n");
      out.write("                                <!--<label for=\"item1\"></label>-->\r\n");
      out.write("                                <!--<span>行政案件</span>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div class=\"sne-radio\">-->\r\n");
      out.write("                                <!--<input id=\"item2\" type=\"radio\" name=\"item\" value=\"行政案件\" >-->\r\n");
      out.write("                                <!--<label for=\"item2\"></label>-->\r\n");
      out.write("                                <!--<span>行政案件</span>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div class=\"sne-radio\">-->\r\n");
      out.write("                                <!--<input id=\"item3\" type=\"radio\" name=\"item\" value=\"当场处罚\" >-->\r\n");
      out.write("                                <!--<label for=\"item3\"></label>-->\r\n");
      out.write("                                <!--<span>当场处罚</span>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div class=\"sne-radio\">-->\r\n");
      out.write("                                <!--<input id=\"item4\" type=\"radio\" name=\"item\" value=\"民事调解\" >-->\r\n");
      out.write("                                <!--<label for=\"item4\"></label>-->\r\n");
      out.write("                                <!--<span>民事调解</span>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div class=\"sne-radio\">-->\r\n");
      out.write("                                <!--<input id=\"item5\" type=\"radio\" name=\"item\" value=\"一般民事纠纷\" >-->\r\n");
      out.write("                                <!--<label for=\"item5\"></label>-->\r\n");
      out.write("                                <!--<span>一般民事纠纷</span>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div class=\"sne-radio\">-->\r\n");
      out.write("                                <!--<input id=\"item6\" type=\"radio\" name=\"item\" value=\"公民求助\" >-->\r\n");
      out.write("                                <!--<label for=\"item6\"></label>-->\r\n");
      out.write("                                <!--<span>公民求助</span>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div class=\"sne-radio\">-->\r\n");
      out.write("                                <!--<input id=\"item7\" type=\"radio\" name=\"item\" value=\"其它\" >-->\r\n");
      out.write("                                <!--<label for=\"item7\"></label>-->\r\n");
      out.write("                                <!--<span>其它</span>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div class=\"sne-radio\">-->\r\n");
      out.write("                                <!--<input id=\"item8\" type=\"radio\" name=\"item\" value=\"所有\" checked>-->\r\n");
      out.write("                                <!--<label for=\"item8\"></label>-->\r\n");
      out.write("                                <!--<span>所有</span>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--echart 1 map-->\r\n");
      out.write("\r\n");
      out.write("                            <div   id=\"data_map_div\" style=\"height: 546px;width:370px;\"></div>\r\n");
      out.write("                            <!--<img src=\"../images/echart_1_map.png\" alt=\"\">-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h464\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--box1 end-->\r\n");
      out.write("\r\n");
      out.write("                <!--box1 start-->\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h93\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">当年人口流出\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2 h180\">\r\n");
      out.write("                            <!--echart 12-->\r\n");
      out.write("                            <!--<img src=\"../images/echart_12.png\" alt=\"\">-->\r\n");
      out.write("                            <div id=\"data_12_div\"  class=\"data_map_div\" style=\"height: 175px;width:370px;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h93\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--box1 end-->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--右-->\r\n");
      out.write("            <div class=\"sne-content-layout3\">\r\n");
      out.write("                <!--box1 start-->\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h142\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">当前迁入省份柱状图\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2 h224\">\r\n");
      out.write("                            <!--echart 8-->\r\n");
      out.write("                            <!--<img src=\"../images/echart_8.png\" alt=\"\">-->\r\n");
      out.write("                            <div id=\"data_8_div\" class=\"liujfdiv liujfchart\" style=\"height: 224px;width:690px;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h142\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--box1 end-->\r\n");
      out.write("\r\n");
      out.write("                <!--box1 start-->\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h142\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">流入人口学历分布\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2 h224\">\r\n");
      out.write("                            <!--echart 9-->\r\n");
      out.write("                            <!--<img src=\"../images/echart_9.png\" alt=\"\">-->\r\n");
      out.write("                            <div id=\"data_9_div\" class=\"liujfdiv liujfchart\" style=\"height: 224px;width:690px;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h142\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"sne-content-box\">\r\n");
      out.write("                    <div class=\"sne-content-box-top1\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l2 h142\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-l3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div  class=\"sne-content-box-top2\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m1\">当年流入人口\r\n");
      out.write("                            <!--<a href=\"#\" class=\"sne-alink fr\">详情</a>-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m2 h224\">\r\n");
      out.write("                            <!--echart 9-->\r\n");
      out.write("                            <!--<img src=\"../images/echart_9.png\" alt=\"\">-->\r\n");
      out.write("                            <div id=\"data_11_div\" class=\"liujfdiv liujfchart\" style=\"height: 224px;width:690px;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-m3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"sne-content-box-top3\">\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r1\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r2 h142\"></div>\r\n");
      out.write("                        <div class=\"sne-sne-content-box-r3\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--box1 end-->\r\n");
      out.write("                <!--<div style=\"width:100%;\">-->\r\n");
      out.write("                    <!--<div style=\"width:49.5%;display:inline-block ;float:left;\">-->\r\n");
      out.write("                        <!--&lt;!&ndash;box1 start&ndash;&gt;-->\r\n");
      out.write("                        <!--<div class=\"sne-content-box\">-->\r\n");
      out.write("                            <!--<div class=\"sne-content-box-top1\">-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-l1\"></div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-l2 h75\"></div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-l3\"></div>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div  class=\"sne-content-box-top2\">-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-m1\">案件审核情况-->\r\n");
      out.write("                                    <!--&lt;!&ndash;<a href=\"#\" class=\"sne-alink fr\">详情</a>&ndash;&gt;-->\r\n");
      out.write("                                <!--</div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-m2 h157\">-->\r\n");
      out.write("                                    <!--&lt;!&ndash;echart 10&ndash;&gt;-->\r\n");
      out.write("                                    <!--&lt;!&ndash;<img src=\"../images/echart_10.png\" alt=\"\">&ndash;&gt;-->\r\n");
      out.write("                                    <!--<div id=\"data_10_div\" class=\"liujfdiv2 liujfchart\" style=\"height: 157px;width:330px;\"></div>-->\r\n");
      out.write("                                <!--</div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-m3\"></div>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div class=\"sne-content-box-top3\">-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-r1\"></div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-r2 h75\"></div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-r3\"></div>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                        <!--</div>-->\r\n");
      out.write("                        <!--&lt;!&ndash;box1 end&ndash;&gt;-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!--</div>-->\r\n");
      out.write("                    <!--<div  style=\"width:49.5%;display:inline-block ;float:right;\">-->\r\n");
      out.write("                        <!--&lt;!&ndash;box1 start&ndash;&gt;-->\r\n");
      out.write("                        <!--<div class=\"sne-content-box\">-->\r\n");
      out.write("                            <!--<div class=\"sne-content-box-top1\">-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-l1\"></div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-l2 h75\"></div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-l3\"></div>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div  class=\"sne-content-box-top2\">-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-m1\">民警执法资格情况-->\r\n");
      out.write("                                    <!--&lt;!&ndash;<a href=\"#\" class=\"sne-alink fr\">详情</a>&ndash;&gt;-->\r\n");
      out.write("                                <!--</div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-m2 h157\">-->\r\n");
      out.write("                                    <!--&lt;!&ndash;echart 13&ndash;&gt;-->\r\n");
      out.write("                                    <!--&lt;!&ndash;<img src=\"../images/echart_13.png\" alt=\"\">&ndash;&gt;-->\r\n");
      out.write("                                    <!--<div id=\"data_13_div\" class=\"liujfdiv2 liujfchart\" style=\"height: 157px;width:330px;\"></div>-->\r\n");
      out.write("                                <!--</div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-m3\"></div>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                            <!--<div class=\"sne-content-box-top3\">-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-r1\"></div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-r2 h75\"></div>-->\r\n");
      out.write("                                <!--<div class=\"sne-sne-content-box-r3\"></div>-->\r\n");
      out.write("                            <!--</div>-->\r\n");
      out.write("                        <!--</div>-->\r\n");
      out.write("                        <!--&lt;!&ndash;box1 end&ndash;&gt;-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!--</div>-->\r\n");
      out.write("                <!--</div>-->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sne-layout-box-middle-right\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sne-layout-box-bottom\">\r\n");
      out.write("        <div class=\"sne-layout-box-bottom-left\"></div>\r\n");
      out.write("        <div class=\"sne-layout-box-bottom-middle\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sne-layout-box-bottom-right\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("  \r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
