/* Generated by Together */

package com.hzjc.wsstruts.type;

/**
 *
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
public class CdsDataTag {
    //{Delphi-ClientDataSet�е�XMLDATA��ʽ}
    public final static String DATA_TAG_DATAPACKET = "DATAPACKET";
    //{�ֶζ���TAG}
    public final static String DATA_TAG_METADATA = "METADATA";
    public final static String DATA_TAG_FIELDS = "FIELDS";
    public final static String DATA_TAG_FIELD = "FIELD";
    public final static String DATA_TAG_ATTRNAME = "attrname";
    public final static String DATA_TAG_FIELDTYPE = "fieldtype";
    public final static String DATA_TAG_SUBTYPE = "SUBTYPE";
    public final static String DATA_TAG_WIDTH = "WIDTH";
    //{����TAG}
    public final static String DATA_TAG_ROWDATA = "ROWDATA";
    public final static String DATA_TAG_ROW = "ROW";
    public final static String DATA_TAG_ROWSTATE = "RowState";
    public final static String DATA_TAG_FIELDTYPE_binhex = "bin.hex";
    public final static String DATA_TAG_BINARY = "Binary";
    //�������е�Tag
    public final static String DATA_TAG_CLASS = "class";
}
