/* Generated by Together */

package com.hzjc.wsstruts.type;

/**
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
public interface PackXQL {

  /**
   *
   * @return
   */
  int getPageoffset();

  /**
   *
   * @param pageoffset
   */
  void setPageoffset(int pageoffset);

  /**
   *
   * @return
   */
  int getPagesize();

  /**
   *
   * @param pagesize
   */
  void setPagesize(int pagesize);

  /**
   *
   * @return
   */
  int getRecordcount();

  /**
   *
   * @param recordcount
   */
  void setRecordcount(int recordcount);


  /**
   *
   * @param strOrderBy
   */
  void addOrderBy(String strOrderBy);

  /**
   *
   * @return
   */
  String getHQLWhere();

  /**
   *
   * @param HQLWhere
   */
  void setHQLWhere(String HQLWhere);
}
