/* Generated by Together */

package com.hzjc.wsstruts.type;

import com.hzjc.wsstruts.exception.*;
import java.util.*;
import java.io.*;
import org.dom4j.io.*;
import org.dom4j.*;
import org.apache.commons.logging.*;
import com.hzjc.wsstruts.vo.*;
import com.hzjc.wsstruts.common.xml.*;
import com.hzjc.util.StringUtils;

/**
 *
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
abstract public class TBaseResponse
    implements TResponse {
  //��־����
  protected static Log _log = LogFactory.getLog(TBaseResponse.class);

  /**
   *
   * @param strIn
   * @return
   */
  protected String toGB13000(String strIn) {
    return StringUtils.toGB13000(strIn);
  }

  /**
   *
   * @param aDoc
   * @param strEncodingName
   * @return
   * @throws <{ActionException}>
   */
  protected String toXML(Document aDoc, String strEncodingName) throws
      ActionException {
    String strXml = "";
    try {
      strXml = XmlUtils.toXML(aDoc, strEncodingName);
    }
    catch (Exception ex) {
      throw new ActionException(WSErrCode.ERR_ACTION_PACKET_SAVETOXML, ex);
    }
    return strXml;
  }

  /**
   *
   * @param name
   * @param objarray
   */
  public abstract void writeToRsData(String name, Object[] objarray) throws
      ActionException;

  /**
   *
   * @param strName
   * @param typeClazz
   * @throws ActionException
   */
  public abstract void writeToRsData(String strName, Class typeClazz) throws
      ActionException;

  /**
   *
   * @param name
   * @param recordcount
   * @param objarray
   * @param typeClazz
   * @throws ActionException
   */
  public abstract void writeToRsData(String name, Long recordcount,
                                     Object[] objarray,
                                     Class typeClazz) throws ActionException;

  /**
   *
   * @param name
   * @param voResult
   * @throws ActionException
   */
  public void writeToRsData(String name, VoQueryResult voResult) throws
      ActionException {
    try {
      if (name != null && voResult != null) {
        Long lRecorCount = new Long(voResult.getRecordcount());
        List lstObj = voResult.getPagelist();
        Object[] arryObjs = null;
        if (lstObj != null) {
          arryObjs = lstObj.toArray();
        }
        Class clazz = voResult.getVotype();
        writeToRsData(name, lRecorCount, arryObjs, clazz);
      }
    }
    catch (ActionException ex) {
      throw ex;
    }
  }

  /**
   *
   * @param strName
   * @param listObj
   * @throws ActionException
   */
  public void writeToRsData(String strName, List listObj) throws
      ActionException {
    if (listObj != null) {
      try {
        writeToRsData(strName, listObj.toArray());
      }
      catch (ActionException ex) {
        throw ex;
      }
    }
  }

  /**
   *
   * @param strName
   * @param obj
   * @throws ActionException
   */
  public void writeToRsData(String strName, Object obj) throws ActionException {
    if (obj != null) {
      try {
        writeToRsData(strName, new Object[] {obj});
      }
      catch (ActionException ex) {
        throw ex;
      }
    }
  }
}
