/* Generated by Together */

package com.hzjc.wsstruts.type;

import org.dom4j.*;

/**
 * ͨ�Ű��ӿ�
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
public interface TPacket
    extends TRequest, TResponse {

  /**
   *
   * @return
   */
  TRequest getRequest();

  /**
   *
   * @param request
   */
  void setRequest(TRequest request);

  /**
   *
   * @return
   */
  TResponse getResponse();

  /**
   *
   * @param response
   */
  void setResponse(TResponse response);
}
