/* Generated by Together */

package com.hzjc.wsstruts.type;

import org.dom4j.*;
import java.util.*;
import com.hzjc.wsstruts.exception.*;
import com.hzjc.wsstruts.vo.CdsVO;
import com.hzjc.wsstruts.vo.VarVO;

/**
 * ������ӿ�
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
public interface TRequest {
  /**
   *
   * @param aXmlData
   * @return
   */
  TRequest loadFromXml(String aXmlData) throws ActionException;

  /**
   *
   * @return
   * @throws ActionException
   */
  String reqSaveToXml() throws ActionException;

  /**
   *
   * @param name
   * @param value
   */
  String readFromHeadNodeAsStr(String name) throws ActionException;

  /**
   *
   * @param name
   * @param value
   */
  Element readFromHeadNodeAsElement(String name) throws ActionException;

  /**
   *
   * @param name
   * @param value
   */
  Element readFromContorlNodeAsElement(String name) throws ActionException;

  /**
   *
   * @param name
   * @param value
   */
  String readFromContorlNodeAsStr(String name) throws ActionException;

  /**
   *
   * @param name
   * @param value
   */
  Element readFromDataNodeAsElement(String name) throws ActionException;

  /**
   *
   * @param name
   * @param value
   */
  String readFromVarDataAsStr(String name) throws ActionException;

  /**
   *
   * @param name
   * @param value
   */
  Element readFromVarDataAsElement(String name) throws ActionException;

  /**
   *
   * @return
   */
  PackXQL readFromVarDataAsXQL(String strXqlName) throws ActionException;

  /**
   *
   * @param name
   * @param value
   */
  String readFromRsDataAsStr(String name) throws ActionException;

  /**
   *
   * @param name
   * @return
   */
  List readFromRsDataAsListVO(String name) throws ActionException;

  /**
   *
   * @return
   * @throws <{ActionException}>
   */
  VarVO readFromVarDataAsVarVO() throws ActionException;

  /**
   *
   * @param name
   * @return
   */
  CdsVO[] readFromRsDataAsArrayVO(String name) throws ActionException;

  /**
   *
   * @return
   */
  String getVer();

  /**
   *
   * @return
   */
  String getDatetime();

  /**
   *
   * @return
   */
  String getAction();

  /**
   *
   * @return
   */
  String getCode();

  /**
   *
   * @return
   */
  String getClientip();

  /**
   *
   * @param strClientIp
   */
  void setClientip(String strClientIp);

  /**
   *
   * @return
   */
  String getAuthinfo();

  /**
   *
   * @return
   */
  Element getVardata();

  /**
   *
   * @return
   */
  Element getRsdata();

  /**
   *
   * @return
   */
  Element getPackData();
}
