/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-03-27 13:59:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gnt.rest.util.CommonUtil;
import java.net.*;
import com.gnt.rest.query.QueryXpUtils;
import com.gnt.rest.service.*;
import java.util.*;
import java.io.*;
import com.gnt.rest.query.*;

public final class query_005fchecksfz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	response.setHeader("Pragma", "No-cache");    
	response.setHeader("Cache-Control", "no-cache");    
	response.setDateHeader("Expires", 0);    
	
	/**
	 dlmjdlm==HZADMIN
	dlmjsfzh==340111198209028514
	dlmjuid==3407000001000000001
	dlmdw==340700000
	sfz==430521201002171234
	dlyhxm==??????
	optype==count
	**/
	
	String optype = request.getParameter("optype");
	String dlmjdlm = request.getParameter("dlmjdlm");
	String dlmjuid = request.getParameter("dlmjuid");
	String dlmdw = request.getParameter("dlmdw");
	String sfzh = request.getParameter("sfzh");
	String dlyhxm = request.getParameter("dlyhxm");
	String dlmjsfzh = request.getParameter("dlmjsfzh");
	
	if(sfzh==null || sfzh.equals("")){
		out.println("<h1>参数错误，身份证号码未知！</h1>");
		return;
	}
	
	
	List<Map<String,String>> list = null;
	String err = "";
	try{
		//身份证查重，只查询有效的
		list = QueryXpUtils.querySfzList(true, request, response);
	}catch(Exception e){
		err = com.gnt.rest.util.CommonUtil.getExceptionMesssage(e);
	}

if("count".equals(optype)){
		if(err.equals("")){
			out.println("{");
			out.println("\"success\":\"true\",");
			out.println("\"count\":\"" + list.size() + "\"");
			out.println("}");
		}else{
			out.println("{");
			out.println("\"success\":\"false\",");
			out.println("\"message\":" + err + "\",");
			out.println("\"count\":\"" + list.size() + "\"");
			out.println("}");
		}
		return;
}else{
	if("fk".equals(optype)){
		Map<String,String> params = new HashMap<String,String>();
		for(Object key:request.getParameterMap().keySet()){
			String value = request.getParameter(key.toString());
			if(value==null) continue;
			
			params.put(key.toString(), value);
		}
		
		LoginService loginService = (LoginService)com.gnt.rest.util.SpringContainer.getObject("loginService");
		loginService.saveSfzchfk(params);
		
		out.println("<h1>反馈成功！</h1>");
		return;
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{background-color:#FFFFFF}\r\n");
      out.write(".div1{width:auto; border:1px; background-color:#D4E1F2; border:#A2BAD6 solid 1px;}\r\n");
      out.write(".div2_title{border-bottom:1px; width:auto; height:30px; line-height:35px; border-bottom:#A2BAD6 solid 1px;}\r\n");
      out.write("strong{margin-left:10px; font-size:12px; color:#324160;}\r\n");
      out.write("\r\n");
      out.write(".div_datainfo{width:99.2%; margin:5px; background-color:#FFFFFF; margin-bottom:0; border:#A2BAD6 solid 1px;}\r\n");
      out.write("table{width:100%; height:auto; font-size:12px; border-collapse:collapse;}\r\n");
      out.write("td{border-right:#C8B9AE solid 1px;border-bottom:#C8B9AE solid 1px; padding:2px 2px 2px;vertical-align: top;}\r\n");
      out.write(".last_td{ border-right:0;}\r\n");
      out.write("thead tr{width:100%; background-color:#EFF0F2;}\r\n");
      out.write(".id{background-color:#EFF0F2;}\r\n");
      out.write("a{text-decoration:none; color:#FF3399; cursor:pointer;}\r\n");
      out.write("\r\n");
      out.write(".footer{width:99.2%; height:20px; margin-left:5px;}\r\n");
      out.write("</style>\r\n");
      out.write("<title>无标题文档</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body style='padding:0;margin:0'>\r\n");
      out.write("<div class=\"div1\">\r\n");
      out.write("<div class=\"div2_title\">身份证重号信息：");
      out.print(sfzh );
      out.write("</div>\r\n");

String str = QueryXpUtils.config.get("SFZCHYY");
if(str==null) str = "";
String[] yystr = str.split("&");

String chsfz = "";
for(Map<String,String> data:list){
	String hjdz_qhnxxdz = data.get("hjdz_qhnxxdz");
	if(hjdz_qhnxxdz==null)
		hjdz_qhnxxdz = "";
	
	chsfz += "," + data.get("gmsfhm");

      out.write("\r\n");
      out.write("<div class=\"div_datainfo\">\r\n");
      out.write("<table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <thead>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td >身份证号</td><td>");
      out.print(QueryXpUtils.getDataValue(data, "gmsfhm") );
      out.write("</td>\r\n");
      out.write("    <td>姓名</td><td>");
      out.print(QueryXpUtils.getDataValue(data,"xm") );
      out.write("</td>\r\n");
      out.write("    <td>性别</td><td>");
      out.print(QueryXpUtils.getDataValue(data,"xbdm") );
      out.write("</td>\r\n");
      out.write("    <td>民族</td><td>");
      out.print(QueryXpUtils.getDataValue(data,"mzdm") );
      out.write("</td>\r\n");
      out.write("   </tr><tr>\r\n");
      out.write("    \t<td>地址</td>\r\n");
      out.write("    \t<td colspan=\"7\">\r\n");
      out.write("    \t\t");
      out.print(hjdz_qhnxxdz);
      out.write("\r\n");
      out.write("    \t</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td>照片</td>\r\n");
      out.write("    <td colspan=7></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    </table>\r\n");
      out.write("    </div>\r\n");
      out.write(" ");
} 
      out.write("\r\n");
      out.write(" <form name=\"form1\" action=\"query_checksfz_save\" method=\"post\">\r\n");
      out.write(" <input type='hidden' name=\"dlmjdlm\" value=\"");
      out.print(dlmjdlm );
      out.write("\" />\r\n");
      out.write(" <input type='hidden' name=\"dlmjuid\" value=\"");
      out.print(dlmjuid );
      out.write("\" />\r\n");
      out.write(" <input type='hidden' name=\"dlmdw\" value=\"");
      out.print(dlmdw );
      out.write("\" />\r\n");
      out.write(" <input type='hidden' name=\"dlmjsfzh\" value=\"");
      out.print(dlmjsfzh );
      out.write("\" />\r\n");
      out.write(" <input type='hidden' name=\"sfzh\" value=\"");
      out.print(chsfz );
      out.write("\" />\r\n");
      out.write(" <input type='hidden' name=\"dlyhxm\" value=\"");
      out.print( dlyhxm);
      out.write("\" />\r\n");
      out.write(" <input type='hidden' name=\"optype\" value=\"fk\" />\r\n");
      out.write(" \r\n");
      out.write(" <div class=\"div2_title\">反馈重号信息</div>\r\n");
      out.write(" <div class=\"div_datainfo\">\r\n");
      out.write("<table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("  <thead>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=100>重号原因：</td><td>\r\n");
      out.write("    \t<select name=\"chyy\">\r\n");
      out.write("    \t\t");

    		for(String s:yystr){
    			String[] s1 = s.split("=");
    			if(s1.length==2){
    				out.println("<option value='" + s1[0] + "'>" + s1[1] + "</option>");
    			}
    			System.out.println(s);
    		}
    		
      out.write("\r\n");
      out.write("    \t</select>\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td >反馈情况：</td><td>\r\n");
      out.write("    \t<textarea name=\"fkqk\" style='width:100%;height:100px'></textarea>\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("   \t<td></td><td colspan=7>\r\n");
      out.write("   \t\t<button type='button' onclick=\"sub()\">反馈重号信息</button>\r\n");
      out.write("   \t</td>\r\n");
      out.write("   </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    </table>\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <script language=\"javascript\">\r\n");
      out.write("    function sub(){\r\n");
      out.write("    \tif(document.form1.fkqk.value==\"\"){\r\n");
      out.write("    \t\talert(\"必须输入反馈情况！\");\r\n");
      out.write("    \t\treturn;\r\n");
      out.write("    \t}\r\n");
      out.write("    \t\r\n");
      out.write("    \tdocument.form1.submit();\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("    </div>\r\n");
      out.write("    </body>\r\n");
      out.write("    </html>\r\n");
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
