/* Generated by Together */

package com.hzjc.hz2004.service;

import com.hzjc.wsstruts.service.*;
import com.hzjc.hz2004.base.login.AuthToken;
import com.hzjc.report.service.ReportService;
import com.hzjc.wsstruts.exception.*;

/**
 *
 * <p>Title: </p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @author not attributable
 * @version 1.0
 */
public class Hz2004ServiceLocator
    extends ServiceLocator {

  //////////////////////////////////////////////////////////////////////////
  //配置文件中的Service-Id
  //////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////
  //框架调用部分
  //////////////////////////////////////////////////////////////////////////
  private static String SERVICE_SYSPARAMCODESERVICE = "sysParamCodeService";
  private static String SERVICE_SYSDATACHECKSERVICE = "sysDataCheckService";
  private static String SERVICE_AUTHTOKENSERVICE = "authTokenService";
  private static String SERVICE_HZ2004SERVICEHELPER = "hz2004ServiceHelper";
  ///////////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////////
  //户籍业务部分
  //////////////////////////////////////////////////////////////////////////
  private static String SERVICE_GYSERVICE = "gyService";
  private static String SERVICE_HJSERVICE = "hjService";
  private static String SERVICE_DZSERVICE = "dzService";
  private static String SERVICE_CXSERVICE = "cxService";
  private static String SERVICE_SPSERVICE = "spService";

  //////////////////////////////////////////////////////////////////////////
  //证件业务部分(一代证、二代证)
  //////////////////////////////////////////////////////////////////////////
  private static String SERVICE_ZJ1SERVICE = "zj1Service";
  private static String SERVICE_ZJ2SERVICE = "zj2Service";

  //////////////////////////////////////////////////////////////////////////
  //报表部分
  /////////////////////////////////////////////////////////////////////////
  private static String SERVICE_REPORTSERVICE = "reportService";

  //////////////////////////////////////////////////////////////////////////
  //系统部分定义
  //////////////////////////////////////////////////////////////////////////
  private static String SERVICE_XTCSSERVICE = "xtcsService";
  private static String SERVICE_XTGNSERVICE = "xtgnService";
  private static String SERVICE_XTKZCSSERVICE = "xtkzcsService";
  private static String SERVICE_XTSJZDSERVICE = "xtsjzdService";
  private static String SERVICE_XTXZQHSERVICE = "xtxzqhService";
  private static String SERVICE_XTDWXXSERVICE = "xtdwxxService";
  private static String SERVICE_XTJWZRQSERVICE = "xtjwzrqService";
  private static String SERVICE_XTXZJDSERVICE = "xtxzjdService";
  private static String SERVICE_XTJWHSERVICE = "xtjwhService";
  private static String SERVICE_XTJLXSERVICE = "xtjlxService";
  private static String SERVICE_XTJLXJWHDZSERVICE = "xtjlxjwhdzService";
  private static String SERVICE_XTYHIPYXSERVICE = "xtyhipyxService";
  private static String SERVICE_XTHHXLSERVICE = "xthhxlService";
  private static String SERVICE_XTBSSQSERVICE = "xtbssqService";
  private static String SERVICE_XTLNWSDSERVICE = "xtlnwsdService";
  private static String SERVICE_XTQYSZSERVICE = "xtqyszService";
  private static String SERVICE_XTSPDZSERVICE = "xtspdzService";
  private static String SERVICE_XTSPMBSERVICE = "xtspmbService";
  private static String SERVICE_XTSPLSERVICE = "xtsplService";
  private static String SERVICE_XTSJPZSERVICE = "xtsjpzService";
  private static String SERVICE_XTYHSERVICE = "xtyhService";
  private static String SERVICE_XTJSSERVICE = "xtjsService";
  private static String SERVICE_XTBBSERVICE = "xtbbService";
  private static String SERVICE_XTYWBLXZSERVICE = "xtywblxzService";
  private static String SERVICE_XTYWQXSERVICE = "xtywqxService";
  private static String SERVICE_XTSLHXLSERVICE = "xtslhxlService";
  private static String SERVICE_XTBGKZSERVICE = "xtbgkzService";

  private static String SERVICE_XTSJCCSERVICE = "XtsjccService";
 //地址追加
  private static String SERVICE_DZZJSERVICE = "DzzjService";
  //临时身份证
  private static String SERVICE_LSSFZSERVICE = "LssfzService";

  private static String SERVICE_LSSERVICE = "LsService";

  private static String SERVICE_YDZZSERVICE = "YdzzService";

  private static String SERVICE_BDXGSERVICE = "BdxgService";

  private static String SERVICE_SMKSERVICE = "SmkService";//市民卡
  private static String SERVICE_PJQSERVICE = "PjqService";//评价器
  private static String SERVICE_ZWSERVICE = "ZwService";//指纹

  private AuthToken authtoken = null;
  //-------------end of 系统部分定义---------------------------

  /////////////////////////////////////////////////////////////////////
  // 服务代理定位的构造方法
  /////////////////////////////////////////////////////////////////////
  //私有静态变量
  private static ServiceLocator _hz2004servicelocator = null;

  /**
   * 保护构造子
   */
  protected Hz2004ServiceLocator() {

  }

  protected Hz2004ServiceLocator(AuthToken authinfo) {
    setAuthtoken(authinfo);
  }

  /////////////////////////////////////////////////////////////////////

  //////////////////////////////////////////////////////////////////////
  //属性部分定义
  //////////////////////////////////////////////////////////////////////
  public AuthToken getAuthtoken() {
    return authtoken;
  }

  public void setAuthtoken(AuthToken authtoken) {
    this.authtoken = authtoken;
  }

  ////////////////////////////////////////////////////////////////////

  /*
    public static synchronized Hz2004ServiceLocator getInstance(AuthToken
        authinfo) {
      if (_hz2004servicelocator == null) {
        _hz2004servicelocator = new Hz2004ServiceLocator(authinfo);
      }
      return (Hz2004ServiceLocator) _hz2004servicelocator;
    }
   */

  /**
   *
   * @return
   */
  public static synchronized Hz2004ServiceLocator getInstance() {
    /**
     * 单例
     */
    if (_hz2004servicelocator == null) {
      _hz2004servicelocator = new Hz2004ServiceLocator();

    }
    return (Hz2004ServiceLocator) _hz2004servicelocator;
  }

  /////////////////////////////////////////////////////////////////////////
  // 框架调用部分
  /////////////////////////////////////////////////////////////////////////
  /**
   *
   * @return
   */
  public SysParamCodeService getSysParamCodeService() {
    return (SysParamCodeService) getService(SERVICE_SYSPARAMCODESERVICE);
  }

  /**
   *
   * @return
   */
  public SysDataCheckService getSysDataCheckService() {
    return (SysDataCheckService) getService(SERVICE_SYSDATACHECKSERVICE);
  }

  /**
   *
   * @return
   */
  public AuthTokenService getAuthTokenService() {
    return (AuthTokenService) getService(SERVICE_AUTHTOKENSERVICE);
  }

  /**
   *
   * @return
   */
  public Hz2004ServiceHelper getHz2004ServiceHelper() {
    return (Hz2004ServiceHelper) getService(SERVICE_HZ2004SERVICEHELPER);
  }

  ///////////////////////////////////////////////////////////////////////////

  /////////////////////////////////////////////////////////////////////////
  // 户籍业务
  //////////////////////////////////////////////////////////////////////////
  /**
   * 公用业务类
   * @return
   */
  public GyService getGyService() {
    return (GyService) getService(SERVICE_GYSERVICE);
  }

  /**
   * 户籍业务类
   * @return
   */
  public HjService getHjService() {
    return (HjService) getService(SERVICE_HJSERVICE);
  }

  /**
   * 地址业务类
   * @return
   */
  public DzService getDzService() {
    return (DzService) getService(SERVICE_DZSERVICE);
  }

  /**
   * 冲销业务类
   * @return
   */
  public CxService getCxService() {
    return (CxService) getService(SERVICE_CXSERVICE);
  }

  /**
   * 审批业务类
   * @return
   */
  public SpService getSpService() {
    return (SpService) getService(SERVICE_SPSERVICE);
  }

  //////////////////////////////////////////////////////////////////
  //系统部分
  //////////////////////////////////////////////////////////////////
  /**
   * 系统参数
   * @return
   */
  public XtcsService getXtcsService() {
    return (XtcsService) getService(SERVICE_XTCSSERVICE);
  }

  /**
   * 系统功能菜单
   * @return
   */
  public XtgnService getXtgnService() {
    return (XtgnService) getService(SERVICE_XTGNSERVICE);
  }

  /**
   * 系统控制参数
   * @return
   */
  public XtkzcsService getXtkzcsService() {
    return (XtkzcsService) getService(SERVICE_XTKZCSSERVICE);
  }

  /**
   * 数据字典参数
   * @return
   */
  public XtsjzdService getXtsjzdService() {
    return (XtsjzdService) getService(SERVICE_XTSJZDSERVICE);
  }

  /**
   * 行政区划信息
   * @return
   */
  public XtxzqhService getXtxzqhService() {
    return (XtxzqhService) getService(SERVICE_XTXZQHSERVICE);
  }

  /**
   * 单位信息
   * @return
   */
  public XtdwxxService getXtdwxxService() {
    return (XtdwxxService) getService(SERVICE_XTDWXXSERVICE);
  }

  /**
   * 警务责任区信息
   * @return
   */
  public XtjwzrqService getXtjwzrqService() {
    return (XtjwzrqService) getService(SERVICE_XTJWZRQSERVICE);
  }

  /**
   * 乡镇街道信息
   * @return
   */
  public XtxzjdService getXtxzjdService() {
    return (XtxzjdService) getService(SERVICE_XTXZJDSERVICE);
  }

  /**
   * 居委会信息
   * @return
   */
  public XtjwhService getXtjwhService() {
    return (XtjwhService) getService(SERVICE_XTJWHSERVICE);
  }

  /**
   * 街路巷信息
   * @return
   */
  public XtjlxService getXtjlxService() {
    return (XtjlxService) getService(SERVICE_XTJLXSERVICE);
  }

  /**
   * 街路巷居委会对着信息
   * @return
   */
  public XtjlxjwhdzService getXtjlxjwhdzService() {
    return (XtjlxjwhdzService) getService(SERVICE_XTJLXJWHDZSERVICE);
  }

  /**
   * 用户IP允许信息
   * @return
   */
  public XtyhipyxService getXtyhipyxService() {
    return (XtyhipyxService) getService(SERVICE_XTYHIPYXSERVICE);
  }

  /**
   * 户号序列信息
   * @return
   */
  public XthhxlService getXthhxlService() {
    return (XthhxlService) getService(SERVICE_XTHHXLSERVICE);
  }

  /**
   * 本市市区信息
   * @return
   */
  public XtbssqService getXtbssqService() {
    return (XtbssqService) getService(SERVICE_XTBSSQSERVICE);
  }

  /**
   * 历年尾数段信息
   * @return
   */
  public XtlnwsdService getXtlnwsdService() {
    return (XtlnwsdService) getService(SERVICE_XTLNWSDSERVICE);
  }

  /**
   * 迁移设置信息
   * @return
   */
  public XtqyszService getXtqyszService() {
    return (XtqyszService) getService(SERVICE_XTQYSZSERVICE);
  }

  /**
   * 审批动作信息
   * @return
   */
  public XtspdzService getXtspdzService() {
    return (XtspdzService) getService(SERVICE_XTSPDZSERVICE);
  }

  /**
   * 审批模板信息
   * @return
   */
  public XtspmbService getXtspmbService() {
    return (XtspmbService) getService(SERVICE_XTSPMBSERVICE);
  }

  /**
   * 审批流信息
   * @return
   */
  public XtsplService getXtsplService() {
    return (XtsplService) getService(SERVICE_XTSPLSERVICE);
  }

  /**
   * 数据配置信息
   * @return
   */
  public XtsjpzService getXtsjpzService() {
    return (XtsjpzService) getService(SERVICE_XTSJPZSERVICE);
  }

  /**
   * 用户信息
   * @return
   */
  public XtyhService getXtyhService() {
    return (XtyhService) getService(SERVICE_XTYHSERVICE);
  }

  /**
   * 用户角色信息
   * @return
   */
  public XtjsService getXtjsService() {
    return (XtjsService) getService(SERVICE_XTJSSERVICE);
  }

  /**
   * 报表信息
   * @return
   */
  public XtbbService getXtbbService() {
    return (XtbbService) getService(SERVICE_XTBBSERVICE);
  }

  /**
   * 业务办理限制信息
   * @return
   */
  public XtywblxzService getXtywblxzService() {
    return (XtywblxzService) getService(SERVICE_XTYWBLXZSERVICE);
  }

  /**
   * 业务权限信息
   * @return
   */
  public XtywqxService getXtywqxService() {
    return (XtywqxService) getService(SERVICE_XTYWQXSERVICE);
  }

  /**
   * 受理号序列信息
   * @return
   */
  public XtslhxlService getXtslhxlService() {
    return (XtslhxlService) getService(SERVICE_XTSLHXLSERVICE);
  }

  /**
   * 变更打印控制，变更审批信息
   * @return
   */
  public XtbgkzService getXtbgkzService() {
    return (XtbgkzService) getService(SERVICE_XTBGKZSERVICE);
  }

  //-----------------end of 系统部分------------------------
  ////////////////////////////////////////////////////////////////////////////
//地址追加部分
  /**
   * 历年尾数段信息
   * @return
   */
  public DzzjService getDzzjService() {
    return (DzzjService) getService(SERVICE_DZZJSERVICE);
  }

  /////////////////////////////////////////////////////////////////////////////
  //报表部分业务服务
  /////////////////////////////////////////////////////////////////////////////
  public ReportService getReportService() throws ServiceException {
    ReportService reportService = null;
    try {
      reportService = (ReportService) getService(SERVICE_REPORTSERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return reportService;
  }
  /**
   * 变动修改
   * @return
   * @throws ServiceException
   */
  public BdxgService getBdxgService() throws ServiceException {
    BdxgService bdxgService = null;
    try {
      bdxgService = (BdxgService) getService(SERVICE_BDXGSERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return bdxgService;
  }
  /**
   * 临时身份证
   * @return
   * @throws ServiceException
   */
  public LssfzService getLssfzService() throws ServiceException {
    LssfzService lssfzService = null;
    try {
      lssfzService = (LssfzService) getService(SERVICE_LSSFZSERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return lssfzService;
  }

  /**
   * 历史信息
   * @return
   * @throws ServiceException
   */
  public LsService getLsService() throws ServiceException {
    LsService lsService = null;
    try {
      lsService = (LsService) getService(SERVICE_LSSERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return lsService;
  }

  ////////////////////////////////////////////////////////////////////////////
  //证件业务（一代证、二代证）
  ////////////////////////////////////////////////////////////////////////////
  /**
   *
   * @return：返回一代证业务调用接口
   */
  public Zj1Service getZj1Service() throws ServiceException {
    Zj1Service zj1 = null;
    try {
      zj1 = (Zj1Service) getService(SERVICE_ZJ1SERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return zj1;
  }

  /**
   *
   * @return：返回二代证业务调用接口
   */
  public Zj2Service getZj2Service() throws ServiceException {
    Zj2Service zj2 = null;
    try {
      zj2 = (Zj2Service) getService(SERVICE_ZJ2SERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return zj2;
  }

  public XtsjccService getXtsjccService() throws ServiceException {
    return (XtsjccService) getService(SERVICE_XTSJCCSERVICE);
  }

  /**
   * 异地二代证信息接口
   * @return
   * @throws ServiceException
   */
  public YdzzService getYdzzService() throws ServiceException {
    YdzzService ydzzService = null;
    try {
      ydzzService = (YdzzService) getService(SERVICE_YDZZSERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return ydzzService;
  }

  /**
   * 市民卡信息接口
   * @return
   * @throws ServiceException
   */
  public SmkService getSmkService() throws ServiceException {
    SmkService smkService = null;
    try {
      smkService = (SmkService) getService(SERVICE_SMKSERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return smkService;
  }

  /**
   * 外围接口
   * @return
   * @throws ServiceException
   */
  public PjqService getPjqService() throws ServiceException {
    PjqService pjqService = null;
    try {
      pjqService = (PjqService) getService(SERVICE_PJQSERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return pjqService;
  }

  /**
   * 指纹接口
   * @return：
   */
  public ZwService getZwService() throws ServiceException {
    ZwService zw = null;
    try {
      zw = (ZwService) getService(SERVICE_ZWSERVICE);
    }
    catch (ServiceException ex) {
      throw ex;
    }
    return zw;
  }


//  private static String SERVICE_ZZZJSERVICE = "ZzzjService";
//
//  public ZzzjService getZzzjService() throws ServiceException {
//    ZzzjService zzzj = null;
//    try {
//      zzzj = (ZzzjService) getService(SERVICE_ZZZJSERVICE);
//      zzzj.setUserInfo(this.authtoken);
//    }
//    catch (ServiceException ex) {
//      throw ex;
//    }
//    return zzzj;
//  }



  //new 2006
  //////////////////////////////////////////////////////////////////////////
  //批量数据导出部分
  /////////////////////////////////////////////////////////////////////////
  private static String SERVICE_DATEDOWNLOAD4QXSERVICE = "DateDownload4QxService";
  private static String SERVICE_DATEDOWNLOAD4CKSERVICE = "DateDownload4CkService";
  private static String SERVICE_DATEDOWNLOAD4SBSERVICE = "DateDownload4SbService";
  private static String SERVICE_DATEDOWNLOAD4SSSERVICE = "DateDownload4SsService";
  private static String SERVICE_DATEDOWNLOAD4PCSERVICE = "DateDownload4PcService";
  private static String SERVICE_DATEDOWNLOAD4XZSERVICE = "DateDownload4XzService";
  private static String SERVICE_DATEDOWNLOAD4JWSERVICE = "DateDownload4JwService";
  private static String SERVICE_DATEDOWNLOAD4JLSERVICE = "DateDownload4JlService";
  private static String SERVICE_DATEDOWNLOAD4ZRSERVICE = "DateDownload4ZrService";
  /////////////////////////////////////////////////////////////////////////
  // 批量数据导出部分
  /////////////////////////////////////////////////////////////////////////
  public DateDownload4QxService getDateDownload4QxService() throws ServiceException {
    return (DateDownload4QxService) getService(SERVICE_DATEDOWNLOAD4QXSERVICE);
  }

  public DateDownload4CkService getDateDownload4CkService() throws ServiceException {
    return (DateDownload4CkService) getService(SERVICE_DATEDOWNLOAD4CKSERVICE);
  }

  public DateDownload4SbService getDateDownload4SbService() throws ServiceException {
    return (DateDownload4SbService) getService(SERVICE_DATEDOWNLOAD4SBSERVICE);
  }

  public DateDownload4SsService getDateDownload4SsService() throws ServiceException {
    return (DateDownload4SsService) getService(SERVICE_DATEDOWNLOAD4SSSERVICE);
  }

  public DateDownload4PcService getDateDownload4PcService() throws ServiceException {
    return (DateDownload4PcService) getService(SERVICE_DATEDOWNLOAD4PCSERVICE);
  }

  public DateDownload4XzService getDateDownload4XzService() throws ServiceException {
    return (DateDownload4XzService) getService(SERVICE_DATEDOWNLOAD4XZSERVICE);
  }

  public DateDownload4JwService getDateDownload4JwService() throws ServiceException {
    return (DateDownload4JwService) getService(SERVICE_DATEDOWNLOAD4JWSERVICE);
  }

  public DateDownload4JlService getDateDownload4JlService() throws ServiceException {
    return (DateDownload4JlService) getService(SERVICE_DATEDOWNLOAD4JLSERVICE);
  }

  public DateDownload4ZrService getDateDownload4ZrService() throws ServiceException {
    return (DateDownload4ZrService) getService(SERVICE_DATEDOWNLOAD4ZRSERVICE);
  }

}
