/* Generated by Together */

package com.hzjc.hz2004.service;

import com.hzjc.wsstruts.exception.*;
import com.hzjc.wsstruts.vo.*;

/**
 * 系统数据逻辑校验接口
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口管理系统Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: 浙江金铖华元新技术有限公司</p>
 * @author kgb_hz@126.com,kgb@primetech.com.cn
 * @version 1.0
 */
public interface SysDataCheckService
    extends Hz2004Service {

  /**
   *
   * @throws ServiceException
   * @throws DAOException
   */
  void checkRkjbxxb() throws ServiceException, DAOException;

  /**
   *
   * @param strHQL
   * @param vopage
   * @return
   * @throws ServiceException
   * @throws DAOException
   */
  VoQueryResult queryRyljjycwxx(String strHQL, VoPage vopage) throws
      ServiceException,
      DAOException;

}
