/* Generated by Together */

package com.hzjc.hz2004.appbase;

import com.hzjc.wsstruts.exception.*;
import org.apache.commons.logging.*;
import com.hzjc.wsstruts.common.config.*;

/**
 * 得到系统运行的配置文件信息
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
public class SysConfig
    extends WSConfig {
  //日志处理
  protected static Log _log = LogFactory.getLog(SysConfig.class);

  private static WSConfig _wscfg = null;

  /**
   *
   */
  protected SysConfig() {
  }

  /**
   *
   * @param cfg
   */
  protected SysConfig(WSConfig cfg) {
    _wscfg = cfg;
  }

  /**
   * 加载所有系统配置
   * @throws ControlException
   */
  public static SysConfig loadAllConfig() throws ControlException {
    try {
      return new SysConfig(WSConfig.getInsance());
    }
    catch (ControlException ex) {
      throw ex;
    }
  }

}
