/* Generated by Together */

package com.hzjc.wsstruts.exception;

/**
 * 从配置文件application.bean.xml文件中加载创建Bean发生异常
 * <p>Title: </p>
 * <p>Description: </p>
 * <p>Copyright: Copyright (c) 2003</p>
 * <p>Company: </p>
 * @Kansanku(kgb_hz@126.com)
 * @version 1.0
 */
public class BeanCreateException
    extends BaseException {

  /**
   *
   */
  public BeanCreateException() {
    super();
  }

  /**
   *
   * @param iErrCode
   * @param e
   */
  public BeanCreateException(int iErrCode, Throwable e) {
    super(iErrCode, e);
  }

  /**
   *
   * @param iErrCode
   * @param s
   * @param e
   */
  public BeanCreateException(int iErrCode, String s, Throwable e) {
    super(iErrCode, s, e);
  }

  /**
   *
   * @param s
   * @param e
   */
  public BeanCreateException(String s, Throwable e) {
    super(s, e);
  }

    public BeanCreateException(String strMsg) {
        super(strMsg);
    }

    public BeanCreateException(int iErrCode) {
        super(iErrCode);
    }
}
