/* Generated by Together */

package com.hzjc.wsstruts.exception;

/**
 *
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
public class ResultNotFoundException
    extends BaseException {

  /**
   *
   */
  public ResultNotFoundException() {
    super();
  }

  /**
   *
   * @param strMsg
   */
  public ResultNotFoundException(String strMsg) {
    super(strMsg);
  }

  /**
   *
   * @param iErrCode
   */
  public ResultNotFoundException(int iErrCode) {
    super(iErrCode);
  }

  /**
   *
   * @param iErrCode
   * @param e
   */
  public ResultNotFoundException(int iErrCode, Throwable e) {
    super(iErrCode, e);
  }

  /**
   *
   * @param iErrCode
   * @param s
   * @param e
   */
  public ResultNotFoundException(int iErrCode, String s, Throwable e) {
    super(iErrCode, s, e);
  }

  /**
   *
   * @param s
   * @param e
   */
  public ResultNotFoundException(String s, Throwable e) {
    super(s, e);
  }
}
