/* Generated by Together */

package com.hzjc.wsstruts.exception;

/**
 * 数据传输对象异常类
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author Kansan Ku(kgb_hz@126.com)
 * @version 1.0
 */
public class VOException
    extends BaseException {
  /**
   *
   * @param iErrCode
   * @param s
   * @param e
   */
  public VOException(int iErrCode, String s, Throwable e) {
    super(iErrCode, s, e);
  }

  /**
   *
   * @param iErrCode
   * @param e
   */
  public VOException(int iErrCode, Throwable e) {
    super(iErrCode, e);
  }

  /**
   *
   */
  public VOException() {
    super();
  }

  /**
   *
   * @param s
   * @param e
   */
  public VOException(String s, Throwable e) {
    super(s, e);
  }

    public VOException(int iErrCode) {
        super(iErrCode);
    }

    public VOException(String strMsg) {
        super(strMsg);
    }
}
