/* Generated by Together */

package com.hzjc.wsstruts.vo;

import java.util.*;

/**
 *
 * <p>Title: Hz2004</p>
 * <p>Description:</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company:</p>
 * @author kgb_hz@126.com,kgb@primetech.com.cn
 * @version 1.0
 */
public class VarVO
    implements VO {

  private Map _mapvar = null;

  /**
   *
   */
  public VarVO() {
  }

  /**
   *
   * @param mapVar
   */
  public VarVO(Map mapVar) {
    setVarmap(mapVar);
  }

  /**
   * Map
   * @return
   */
  public Map getVarmap() {
    return _mapvar;
  }

  /**
   *
   * @param varmap
   */
  public void setVarmap(Map varmap) {
    this._mapvar = varmap;
  }

  /**
   *ֵ
   * @param strVarName
   * @return
   */
  public String getVarValue(String strVarName) {
    String strVarValue = null;
    //
    if (strVarName == null || _mapvar == null) {
      return strVarValue;
    }
    //
    if (_mapvar != null) {
      Object objVarValue = _mapvar.get(strVarName);
      if (objVarValue != null) {
        strVarValue = String.valueOf(objVarValue);
      }else {
    	  strVarValue="";
      }
    }
    return strVarValue;
  }

}
