/* Generated by Together */

package com.hzjc.wsstruts.vo;


public class VoPage
    implements VO ,java.io.Serializable{
  private static final long serialVersionUID = 1L;

  private int pageoffset = 0;
  private int pagesize = 20;
  private long recordcount = -1;
  private String hzywid = null;
  private int pageindex = 0;
  
  public int getPageindex() {
	return pageindex;
}

public void setPageindex(int pageindex) {
	this.pageindex = pageindex;
}

public static long getSerialversionuid() {
	return serialVersionUID;
}

public int getPageoffset() {
    return pageoffset;
  }

  public void setPageoffset(int pageoffset) {
    this.pageoffset = pageoffset;
  }

  public int getPagesize() {
    return pagesize;
  }

  public void setPagesize(int pagesize) {
    this.pagesize = pagesize;
  }

  public long getRecordcount() {
    return recordcount;
  }

  public String getHzywid() {
    return hzywid;
  }

  public void setRecordcount(long recordcount) {
    this.recordcount = recordcount;
  }

  public void setHzywid(String hzywid) {
    this.hzywid = hzywid;
  }

}
