/* Generated by Together */

package com.hzjc.hz2004.service.impl;

import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Date;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.List;
import java.util.Map;

import org.apache.commons.beanutils.BeanUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.LockOptions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.hzjc.hz2004.base.ExtMap;
import com.hzjc.hz2004.base.Page;
import com.hzjc.hz2004.base.SimpleJson;
import com.hzjc.hz2004.base.login.AuthToken;
import com.hzjc.hz2004.base.login.BaseContext;
//闵红斌增加
import com.hzjc.hz2004.common.HjCommon;
import com.hzjc.hz2004.constant.HjConstant;
import com.hzjc.hz2004.constant.PublicConstant;
import com.hzjc.hz2004.constant.ZjConstant;
import com.hzjc.hz2004.dao.DAOFactory;
import com.hzjc.hz2004.dao.PojoInfo;
import com.hzjc.hz2004.po.PoHJXX_CZRKJBXXB;
import com.hzjc.hz2004.po.PoHJXX_CZRKJBXXB_DYLS;
import com.hzjc.hz2004.po.PoHJXX_MLPXXXXB;
import com.hzjc.hz2004.po.PoHJXX_PZRZB;
import com.hzjc.hz2004.po.PoHJXX_RYZPXXB;
import com.hzjc.hz2004.po.PoHJXX_ZPLSB;
import com.hzjc.hz2004.po.PoHZ_ZJ_SB;
import com.hzjc.hz2004.po.PoHZ_ZJ_SBZB;
import com.hzjc.hz2004.po.PoLODOP;
import com.hzjc.hz2004.po.PoVIEW_ZZST;
import com.hzjc.hz2004.po.PoV_HJ_CHCLXXB;
import com.hzjc.hz2004.po.PoV_HJ_GMSFHMSXMFPXXB;
import com.hzjc.hz2004.po.PoV_HJ_RDXXB;
import com.hzjc.hz2004.po.PoV_ZJ_GSXXB;
import com.hzjc.hz2004.po.PoV_ZJ_JMSFZXXB;
import com.hzjc.hz2004.po.PoV_ZJ_LQFFXXB;
import com.hzjc.hz2004.po.PoV_ZJ_SHQFXXB;
import com.hzjc.hz2004.po.PoV_ZJ_SJXXB;
import com.hzjc.hz2004.po.PoV_ZJ_XHXXB;
import com.hzjc.hz2004.po.PoV_ZJ_YSXXB;
import com.hzjc.hz2004.po.PoV_ZJ_ZZHKXXB;
import com.hzjc.hz2004.po.PoXT_DWXXB;
import com.hzjc.hz2004.po.PoXT_JWHXXB;
import com.hzjc.hz2004.po.PoXT_XTKZCSB;
import com.hzjc.hz2004.po.PoYDZJ_DBLKZ;
import com.hzjc.hz2004.po.PoYDZJ_SBXXB;
import com.hzjc.hz2004.po.PoYDZJ_SDZP;
import com.hzjc.hz2004.po.PoZJSH_SHQFXXB;
import com.hzjc.hz2004.po.PoZJXX_JMSFZXXB;
import com.hzjc.hz2004.po.PoZJYW_GSXXB;
import com.hzjc.hz2004.po.PoZJYW_LQFFXXB;
import com.hzjc.hz2004.po.PoZJYW_SJXXB;
import com.hzjc.hz2004.po.PoZJYW_SLXXB;
import com.hzjc.hz2004.po.PoZJYW_XHXXB;
import com.hzjc.hz2004.po.PoZJYW_YSXXB;
import com.hzjc.hz2004.po.notable.PoOLD_HJXX_CZRKJBXXB;
import com.hzjc.hz2004.po.notable.PoSB_JMSFZXXB;
import com.hzjc.hz2004.service.DymbwhService;
import com.hzjc.hz2004.service.LoginService;
import com.hzjc.hz2004.service.Zj2Service;
import com.hzjc.hz2004.util.CommonUtil;
import com.hzjc.hz2004.util.DateHelper;
import com.hzjc.hz2004.vo.VoBggzfhxxEx;
import com.hzjc.hz2004.vo.VoBggzxx;
import com.hzjc.hz2004.vo.VoBggzxxEx;
import com.hzjc.hz2004.vo.VoBgryfhxx;
import com.hzjc.hz2004.vo.VoHJXX_CZRKJBXXB;
import com.hzjc.hz2004.vo.VoHJXX_RYZPXXB;
import com.hzjc.hz2004.vo.VoHJXX_SMKZPB;
import com.hzjc.hz2004.vo.VoHJXX_ZPLSB;
import com.hzjc.hz2004.vo.VoLsSfzDybzfhxx;
import com.hzjc.hz2004.vo.VoXT_XTCSB;
import com.hzjc.hz2004.vo.VoXtsjfw;
import com.hzjc.hz2004.vo.VoYdslDblkzfhxx;
import com.hzjc.hz2004.vo.VoYdslzffhxx;
import com.hzjc.hz2004.vo.VoYdslzfxx;
import com.hzjc.hz2004.vo.VoYdslzfywfhxx;
import com.hzjc.hz2004.vo.VoYdzjlqhqxx;
import com.hzjc.hz2004.vo.VoYdzjlqywfhxx;
import com.hzjc.hz2004.vo.VoYdzjsbxx;
import com.hzjc.hz2004.vo.VoZJYW_SLXXB;
import com.hzjc.hz2004.vo.VoZjClddyxx;
import com.hzjc.hz2004.vo.VoZjSlSlztfhxx;
import com.hzjc.hz2004.vo.VoZjdbzffhxx;
import com.hzjc.hz2004.vo.VoZjdbzfxx;
import com.hzjc.hz2004.vo.VoZjdbzfywfhxx;
import com.hzjc.hz2004.vo.VoZjgsfhxx;
import com.hzjc.hz2004.vo.VoZjgsxx;
import com.hzjc.hz2004.vo.VoZjgsywfhxx;
import com.hzjc.hz2004.vo.VoZjlqfffhxx;
import com.hzjc.hz2004.vo.VoZjlqffxx;
import com.hzjc.hz2004.vo.VoZjlqffywfhxx;
import com.hzjc.hz2004.vo.VoZjshfhxx;
import com.hzjc.hz2004.vo.VoZjshxx;
import com.hzjc.hz2004.vo.VoZjshywfhxx;
import com.hzjc.hz2004.vo.VoZjsjfhxx;
import com.hzjc.hz2004.vo.VoZjsjxx;
import com.hzjc.hz2004.vo.VoZjsjywfhxx;
import com.hzjc.hz2004.vo.VoZjslfhxx;
import com.hzjc.hz2004.vo.VoZjslxx;
import com.hzjc.hz2004.vo.VoZjslywfhxx;
import com.hzjc.hz2004.vo.VoZjslzffhxx;
import com.hzjc.hz2004.vo.VoZjslzfxx;
import com.hzjc.hz2004.vo.VoZjslzfywfhxx;
import com.hzjc.hz2004.vo.VoZjxhfhxx;
import com.hzjc.hz2004.vo.VoZjxhxx;
import com.hzjc.hz2004.vo.VoZjxhywfhxx;
import com.hzjc.hz2004.vo.VoZjysfhxx;
import com.hzjc.hz2004.vo.VoZjysxx;
import com.hzjc.hz2004.vo.VoZjysywfhxx;
import com.hzjc.util.StringUtils;
import com.hzjc.wsstruts.KDSActionProxy;
import com.hzjc.wsstruts.common.db.DbUtils;
import com.hzjc.wsstruts.dao.hibernate.DefaultDAO;
import com.hzjc.wsstruts.exception.DAOException;
import com.hzjc.wsstruts.exception.ServiceException;
import com.hzjc.wsstruts.exception.WSErrCode;
import com.hzjc.wsstruts.vo.VoPage;
import com.hzjc.wsstruts.vo.VoQueryResult;


@Service
public class DymbwhServiceImpl
extends ZjBaseService
    implements DymbwhService {
  private static Map dwmap = new Hashtable();

  @Autowired
  private LoginService loginService;
  
  //日志处理
  protected static Log _log = LogFactory.getLog(DymbwhServiceImpl.class);


  
  
  public void updateLodop(Map param,SimpleJson sj)  {
	  try{
		  String id = (String) param.get("id");//new String( ( (String) param.get("id")).getBytes("iso-8859-1"),"GBK");
		  String lodopId = (String) param.get("lodopId");//new String( ( (String) param.get("lodopId")).getBytes("iso-8859-1"),"GBK");
		  String nr =   (String) param.get("nr");
//		  if(zxyy!=null && !param.containsKey("charset")){
//			  zxyy = new String( ( (String) param.get("zxyy")).getBytes("iso-8859-1"),
//					  "GBK");
//		  };
		  if(id==null || id.trim().equals("")||lodopId==null || lodopId.trim().equals(""))
			  throw new  Exception("参数错误！");
		  /////////////////////////////////////////////////////////////////
		  //开始事务
		  /////////////////////////////////////////////////////////////////
		  
		  //////////////////////////////////////////////////////////////////
		  //4、调用DAO查询
		  //////////////////////////////////////////////////////////////////
		  
		  //创建调用的DAO
		  DefaultDAO dao = new DefaultDAO();
			  
		  List list =super.findAllByHQL("from PoLODOP a where a.id='" + id +"' and a.lodopId = '"+lodopId+"'");
		  if(list.size()>0){
			  PoLODOP lodop = (PoLODOP)list.get(0);
			  lodop.setNr(nr);
			  lodop.setXgsj( new SimpleDateFormat("yyyyMMdd").format(new Date()));
			  lodop.setXgr(this.getUser().getYhid()+"");
			  super.update(lodop);
		  }
		  
		  /////////////////////////////////////////////////////////////////
		  //提交事务
		  /////////////////////////////////////////////////////////////////
	  }
	  catch (Exception ex) {
		  //回滚事务
		  throw new java.lang.RuntimeException(ex);
	  }
  }
  @Override
  public void insertLodop(Map param,SimpleJson sj)  {
	  try{
		  String nr =   (String) param.get("nr");
		  String lodopId = (String) param.get("lodopId");
		  String lodopName = (String) param.get("lodopName");
		  String version =   (String) param.get("version");
		  String position =   (String) param.get("position");
		  String pageSize =   (String) param.get("printpageSize");
		  if(nr==null || nr.trim().equals("")||lodopId==null || lodopId.trim().equals(""))
			  throw new  Exception("参数错误！");
		  //nr.replaceAll("LODOP.PRINT_INIT(\"\");", "");//LODOP.PRINT_INIT("");
		  String PRINT_INITA= "LODOP.PRINT_INITA("+position+",\""+lodopId+version+"\");\r\n";
		  String SET_PRINT_PAGESIZE = "";
		  if(pageSize!=null) {
			  SET_PRINT_PAGESIZE = "LODOP.SET_PRINT_PAGESIZE"+pageSize+";\r\n";
		  }
		  //创建调用的DAO
		  DefaultDAO dao = new DefaultDAO();
			  
		  List list =super.findAllByHQL("from PoLODOP a order by a.id  desc ");
		  if(list.size()>0){
			  PoLODOP lodop = (PoLODOP)list.get(0);
			  PoLODOP lodopNew = new PoLODOP();
			  lodopNew.setId((Long.parseLong(lodop.getId())+1)+"");
			  lodopNew.setLodopId(lodopId);
			  lodopNew.setLodopName(lodopName);
//			  String temp = nr.replaceAll("LODOP.PRINT_INIT(\"\");", "");
			  String temp = nr.replace("LODOP.PRINT_INIT(\"\");\r\n", "");
			  lodopNew.setNr(PRINT_INITA+SET_PRINT_PAGESIZE+temp);
			  lodopNew.setZxbz("0");
			  lodopNew.setCjr(this.getUser().getYhid()+"");
			  lodopNew.setCjsj(new SimpleDateFormat("yyyyMMdd").format(new Date()));
			  super.create(lodopNew);
		  }
		  
		  /////////////////////////////////////////////////////////////////
		  //提交事务
		  /////////////////////////////////////////////////////////////////
	  }
	  catch (Exception ex) {
		  //回滚事务
		  throw new java.lang.RuntimeException(ex);
	  }
  }
  public void dealLodop(Map param)  {
    try{
        String lodopId = (String)param.get("lodopId");
        String id = (String)param.get("id");
        if(id==null || id.trim().equals(""))
          throw new  Exception("参数错误！");

        	String hql = "from " + PoLODOP.class.getName() + " a where a.id = '"+id+"' and a.lodopId = '"+lodopId+"'";
	        List list =super.findAllByHQL(hql);
	        if(list.size()>0){
	        	PoLODOP lodop = (PoLODOP)list.get(0);
	        	if(list.size()>0){
	  			  lodop.setZxbz("1");
	  			  lodop.setXgsj(new SimpleDateFormat("yyyyMMdd").format(new Date()));
	  			  lodop.setXgr(this.getUser().getYhid()+"");
	  			  super.update(lodop);
	  		  }
	        	
	        	
        }
        
        /////////////////////////////////////////////////////////////////
        //提交事务
        /////////////////////////////////////////////////////////////////
      }
      catch (Exception ex) {
        //回滚事务
        throw new java.lang.RuntimeException(ex);
      }
  }

}
