/* Generated by Together */

package com.hzjc.hz2004.service.impl;

import com.hzjc.wsstruts.exception.*;
import com.hzjc.hz2004.dao.*;
import com.hzjc.hz2004.po.*;
import com.hzjc.hz2004.po.notable.PoOLD_HJXX_CZRKJBXXB;
import com.hzjc.util.StringUtils;
import com.hzjc.hz2004.constant.*;
import java.util.*;

import org.hibernate.LockOptions;

import com.hzjc.wsstruts.vo.*;
import com.hzjc.hz2004.vo.*;
import com.hzjc.wsstruts.dao.hibernate.DefaultDAO;
import com.hzjc.hz2004.appbase.*;
import com.hzjc.hz2004.base.SpringContextHolder;
import com.hzjc.hz2004.base.login.BaseContext;
import com.hzjc.hz2004.service.ZjService;

/**
 *
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口管理系统Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: 浙江金铖新技术有限公司</p>
 * @author kgb_hz@126.com,kgb@primetech.com.cn
 * @version 1.0
 * @since history 2004-07-01 修改保存证件流水-身份证业务操作表
 *                2004-11-04 修改地址拼装规则:乡镇街道(XZJD),居委会(JWH)==>说明描述取备注字段
 */
abstract public class DymbBaseService
    extends Hz2004BaseService
    implements ZjService {}
