/* Generated by Together */

package com.hzjc.wsstruts.dao.hibernate;
import org.apache.commons.logging.*;

/**
 *
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口管理系统Hz2004版</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: 浙江金铖华元新技术有限公司</p>
 * @author kgb_hz@126.com,kgb@primetech.com.cn
 * @version 1.0
 */
public class DefaultDAO
    extends BaseHibernateDAO {
  //日志处理
  protected Log _log = LogFactory.getLog(this.getClass());

  //////////////////////////////////////////////////////////////////////////////
  //事务处理:在数据访问层界定事务处理，利用ThreadLocal进行事务包装
  /////////////////////////////////////////////////////////////////////////////
}
