/* Generated by Together */

package com.hzjc.hz2004.vo;

import com.hzjc.wsstruts.vo.*;
import com.hzjc.hz2004.po.PoXT_SJPZB;

/**
 *
 * <p>Title: Hz2004</p>
 * <p>Description: 常住人口二代证Hz2004版
 *                 系统数据字典</p>
 * <p>Copyright: Copyright (c) 2004</p>
 * <p>Company: HZJC</p>
 * @author huhua(hh_hz@126.com)
 * @version 1.0
 */
/**
 * @author Administrator
 *
 */
/**
 * @author Administrator
 *
 */
public class VoXT_SJPZB
    extends DefaultVO {
  public VoXT_SJPZB(PoXT_SJPZB poXt_Sjpzb) {
    super(poXt_Sjpzb);
  }
  private Long	sjpzid;
	private String	pzlb;
	private String	pzmc;
	private String	id;
	private String	fieldname;
	private String	displayname;
	private String	fieldtype;
	private String	fieldtypename;
	private String	dsname;
	private String	readonly;
	private String	visibletype;
	private String	fieldlength;
	private String	displayfieldlength;
	private String	ischinese;
	private String	mbmod;
	private String	allowselfinput;
	private String	codefield;
	private String	pyfield;
	private String	namefield;
	private String	partmask;
	private String	lsfield;
	private String	showls;
	private String	enablecopy;
	private String	enabledefaultfilter;
	private String	enterdropdown;
	private String	enteruniqueexit;
	private String	usetablefiltered;
	private String	useforsfz;
	private String	conditionoperator;
	private String	conditionfield;
	private String	conditiontype;
	private String	groups;
	private String	bdlx;
	private String	bdsj;
	private String  vtype;
	private String  pxid;//默认为sjpzid，用于自定义显示gird的时候，排序用
	public String getVtype() {
		return vtype;
	}

	public void setVtype(String vtype) {
		this.vtype = vtype;
	}

	public Long getSjpzid(){
		return this.sjpzid;
	}

	public void setSjpzid(Long sjpzid){
		this.sjpzid=sjpzid;
	}

	public String getPzlb(){
		return this.pzlb;
	}

	public void setPzlb(String pzlb){
		this.pzlb=pzlb;
	}

	public String getPzmc(){
		return this.pzmc;
	}

	public void setPzmc(String pzmc){
		this.pzmc=pzmc;
	}

	public String getId(){
		return this.id;
	}

	public void setId(String id){
		this.id=id;
	}

	public String getFieldname(){
		return this.fieldname;
	}

	public void setFieldname(String fieldname){
		this.fieldname=fieldname;
	}

	public String getDisplayname(){
		return this.displayname;
	}

	public void setDisplayname(String displayname){
		this.displayname=displayname;
	}

	public String getFieldtype(){
		return this.fieldtype;
	}

	public void setFieldtype(String fieldtype){
		this.fieldtype=fieldtype;
	}

	public String getFieldtypename(){
		return this.fieldtypename;
	}

	public void setFieldtypename(String fieldtypename){
		this.fieldtypename=fieldtypename;
	}

	public String getDsname(){
		return this.dsname;
	}

	public void setDsname(String dsname){
		this.dsname=dsname;
	}

	public String getReadonly(){
		return this.readonly;
	}

	public void setReadonly(String readonly){
		this.readonly=readonly;
	}

	public String getVisibletype(){
		return this.visibletype;
	}

	public void setVisibletype(String visibletype){
		this.visibletype=visibletype;
	}

	public String getFieldlength(){
		return this.fieldlength;
	}

	public void setFieldlength(String fieldlength){
		this.fieldlength=fieldlength;
	}

	public String getDisplayfieldlength(){
		return this.displayfieldlength;
	}

	public void setDisplayfieldlength(String displayfieldlength){
		this.displayfieldlength=displayfieldlength;
	}

	public String getIschinese(){
		return this.ischinese;
	}

	public void setIschinese(String ischinese){
		this.ischinese=ischinese;
	}

	public String getMbmod(){
		return this.mbmod;
	}

	public void setMbmod(String mbmod){
		this.mbmod=mbmod;
	}

	public String getAllowselfinput(){
		return this.allowselfinput;
	}

	public void setAllowselfinput(String allowselfinput){
		this.allowselfinput=allowselfinput;
	}

	public String getCodefield(){
		return this.codefield;
	}

	public void setCodefield(String codefield){
		this.codefield=codefield;
	}

	public String getPyfield(){
		return this.pyfield;
	}

	public void setPyfield(String pyfield){
		this.pyfield=pyfield;
	}

	public String getNamefield(){
		return this.namefield;
	}

	public void setNamefield(String namefield){
		this.namefield=namefield;
	}

	public String getPartmask(){
		return this.partmask;
	}

	public void setPartmask(String partmask){
		this.partmask=partmask;
	}

	public String getLsfield(){
		return this.lsfield;
	}

	public void setLsfield(String lsfield){
		this.lsfield=lsfield;
	}

	public String getShowls(){
		return this.showls;
	}

	public void setShowls(String showls){
		this.showls=showls;
	}

	public String getEnablecopy(){
		return this.enablecopy;
	}

	public void setEnablecopy(String enablecopy){
		this.enablecopy=enablecopy;
	}

	public String getEnabledefaultfilter(){
		return this.enabledefaultfilter;
	}

	public void setEnabledefaultfilter(String enabledefaultfilter){
		this.enabledefaultfilter=enabledefaultfilter;
	}

	public String getEnterdropdown(){
		return this.enterdropdown;
	}

	public void setEnterdropdown(String enterdropdown){
		this.enterdropdown=enterdropdown;
	}

	public String getEnteruniqueexit(){
		return this.enteruniqueexit;
	}

	public void setEnteruniqueexit(String enteruniqueexit){
		this.enteruniqueexit=enteruniqueexit;
	}

	public String getUsetablefiltered(){
		return this.usetablefiltered;
	}

	public void setUsetablefiltered(String usetablefiltered){
		this.usetablefiltered=usetablefiltered;
	}

	public String getUseforsfz(){
		return this.useforsfz;
	}

	public void setUseforsfz(String useforsfz){
		this.useforsfz=useforsfz;
	}

	public String getConditionoperator(){
		return this.conditionoperator;
	}

	public void setConditionoperator(String conditionoperator){
		this.conditionoperator=conditionoperator;
	}

	public String getConditionfield(){
		return this.conditionfield;
	}

	public void setConditionfield(String conditionfield){
		this.conditionfield=conditionfield;
	}

	public String getConditiontype(){
		return this.conditiontype;
	}

	public void setConditiontype(String conditiontype){
		this.conditiontype=conditiontype;
	}

	public String getGroups(){
		return this.groups;
	}

	public void setGroups(String groups){
		this.groups=groups;
	}

	public String getBdlx(){
		return this.bdlx;
	}

	public void setBdlx(String bdlx){
		this.bdlx=bdlx;
	}

	public String getBdsj(){
		return this.bdsj;
	}
	public void setBdsj(String bdsj){
		this.bdsj=bdsj;
	}

	public String getPxid() {
		return pxid;
	}

	public void setPxid(String pxid) {
		this.pxid = pxid;
	}
 

}
